# Change these first
owner: longforme # Your GitHub organization or username, where this repository lives
repo: longforme-uptime-monitor # The name of this repository

sites:
  - name: Long Forme
    url: https://longforme.com
  - name: JAU
    url: https://www.jau.co.jp
  - name: Addition Studio
    url: https://additionstudio.jau.co.jp
  - name: Subtle Bodies
    url: https://subtle-bodies.jau.co.jp
  - name: Seljak
    url: https://seljak.jau.co.jp
  - name: KeepCup
    url: https://keepcup.eco.jau.co.jp
  - name: Posie
    url: https://posie.jau.co.jp
  - name: Botanica
    url: https://botanica.jau.co.jp
  - name: Champ
    url: https://champ.jau.co.jp
  - name: Northern Light
    url: https://northernlight.jau.co.jp
  - name: MAHO
    url: https://maho.jau.co.jp
  - name: HHHWWW
    url: https://hhhwww.jp
  - name: HHHWWW store
    url: https://hhhwww.jau.co.jp


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /longforme-uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Long Forme Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
